# Generated by Django 6.0.1 on 2026-01-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_category_type_alter_transaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
