# Generated by Django 6.0.1 on 2026-01-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgae',
            new_name='image',
        ),
    ]
